# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.model_mixins
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('common', '0001_initial'),
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', model_utils.fields.StatusField(choices=[('crew', 'crew'), ('cast', 'cast')], default='crew', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('department', models.CharField(max_length=64)),
                ('job', models.CharField(max_length=64)),
                ('character', models.CharField(blank=True, max_length=128)),
                ('cast_id', models.PositiveIntegerField(blank=True, help_text='number of role in a movie', null=True)),
                ('tmdb_credit_id', models.CharField(max_length=24, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=999)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main title which will be shoved on website', max_length=128)),
                ('release_status', models.CharField(max_length=16)),
                ('release_date', models.DateField(blank=True)),
            ],
            bases=(helpers.model_mixins.PublishedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('certification', models.CharField(help_text='different countries have differrent certification', max_length=16)),
                ('iso_3166_1', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_1', models.CharField(max_length=2)),
                ('iso_639_1', models.CharField(max_length=2)),
                ('key', models.CharField(max_length=32)),
                ('site', models.CharField(max_length=32)),
                ('type', models.CharField(max_length=32)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=999)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movies.Movie')),
                ('original_title', models.CharField(help_text='Title in original language', max_length=128)),
                ('title_ua', models.CharField(blank=True, max_length=128)),
                ('title_ru', models.CharField(blank=True, max_length=128)),
                ('overview', models.TextField(blank=True)),
                ('overview_ua', models.TextField(blank=True)),
                ('tagline', models.CharField(max_length=255)),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.PositiveIntegerField(help_text='Total budget in dollars', null=True)),
                ('revenue', models.PositiveIntegerField(help_text='Total revenue in dollars', null=True)),
                ('revenue_ua', models.PositiveIntegerField(help_text='Revenue in Ukraine', null=True)),
                ('homepage', models.URLField(blank=True)),
                ('original_language', models.CharField(blank=True, max_length=2)),
                ('runtime', models.PositiveIntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=16)),
                ('tmdb_popularity', models.FloatField(blank=True, help_text='Popularity in themoviedb', null=True)),
                ('popularity', models.FloatField(blank=True, help_text='Populatity in this website', null=True)),
                ('vote_average', models.FloatField(blank=True, null=True)),
                ('vote_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='release',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='common.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='movie_image', to='images.Image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(to='common.KeyWord'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='main poster for this movie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_poster', to='images.Image'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(to='common.ProductionCompany'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(to='common.Country'),
        ),
        migrations.AddField(
            model_name='credit',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='credit',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
