# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170623_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='movie_image', to='images.Image'),
        ),
    ]
