# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20170629_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
