# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170701_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='info',
            name='title_ua',
        ),
        migrations.AddField(
            model_name='info',
            name='translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='info',
            name='homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='original_language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='original_title',
            field=models.CharField(blank=True, help_text='Title in original language', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='overview_ua',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='tagline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
