# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20170701_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
