# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_id', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=128)),
                ('name_ua', models.CharField(max_length=128)),
                ('biography', models.TextField(blank=True)),
                ('birthday', models.DateField(blank=True)),
                ('deathday', models.DateField(blank=True)),
                ('gender', models.PositiveSmallIntegerField(blank=True, help_text='1- female, 2- male', null=True)),
                ('homepage', models.URLField(blank=True)),
                ('poster', models.ImageField(blank=True, help_text='main photo for this star', upload_to='images')),
            ],
            bases=(helpers.model_mixins.PublishedMixin, models.Model),
        ),
    ]
