# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='main photo for this star', on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
