# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20170623_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb', models.CharField(blank=True, max_length=32)),
                ('facebook', models.CharField(blank=True, max_length=32)),
                ('instagram', models.CharField(max_length=32)),
                ('twitter', models.CharField(blank=True, max_length=32)),
                ('freebase', models.CharField(blank=True, max_length=32)),
                ('tv_rage', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='star',
            name='imdb_id',
        ),
        migrations.AddField(
            model_name='star',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='star',
            name='translated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='star',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='socialids',
            name='star',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stars.Star'),
        ),
    ]
