# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0003_auto_20170629_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='deathday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
