# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0005_auto_20170629_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialids',
            name='facebook',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socialids',
            name='freebase',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socialids',
            name='imdb',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socialids',
            name='instagram',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socialids',
            name='tv_rage',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='socialids',
            name='twitter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
