# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0007_auto_20170630_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
