# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0008_auto_20170630_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
