# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to='images')),
                ('aspect_ratio', models.FloatField(null=True)),
                ('iso_639_1', models.CharField(blank=True, max_length=2)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=99)),
            ],
        ),
    ]
