# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='aspect_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
