# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20170623_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='p/w'),
        ),
    ]
