# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20170630_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(max_length=255, upload_to='p/w'),
        ),
    ]
